Update ngx_http_captcha_module.c
RekGRpth/ngx_http_captcha_module pull request #1
Opened 2023-10-11 15:26 UTC by vvvllll

attempt to make secret complex

2023-10-11 16:47 UTC, RekGRpth requested changes

2023-10-11 16:47 UTC, RekGRpth commented on ngx_http_captcha_module.c
> +    ngx_http_complex_value(r, location->secret, &secretval);
```suggestion
    if (ngx_http_complex_value(r, location->secret, &secret) != NGX_OK) { ngx_log_error(NGX_LOG_ERR, r->connection->log, 0, "ngx_http_complex_value != NGX_OK"); return NGX_HTTP_INTERNAL_SERVER_ERROR; }
```

2023-10-11 16:47 UTC, RekGRpth commented on ngx_http_captcha_module.c
> +    ngx_str_t               secretval;
```suggestion
    ngx_str_t secret;
```

2023-10-11 16:47 UTC, RekGRpth commented on ngx_http_captcha_module.c
> +    ngx_log_error(NGX_LOG_WARN, r->connection->log, 0, "secret0 %s", code);
```suggestion
```

2023-10-11 16:47 UTC, RekGRpth commented on ngx_http_captcha_module.c
> +    (void)ngx_md5_update(&md5, (const void *)&secretval, secretval.len);
```suggestion
    (void)ngx_md5_update(&md5, (const void *)&secret.data, secret.len);
```

2023-10-11 16:47 UTC, RekGRpth commented on ngx_http_captcha_module.c
> +    if (conf->secret == NULL) {
```suggestion
    if (!conf->secret) conf->secret = prev->secret;
```

2023-10-11 16:47 UTC, RekGRpth commented on ngx_http_captcha_module.c
> +        conf->secret = prev->secret;
```suggestion
```

2023-10-11 16:47 UTC, RekGRpth commented on ngx_http_captcha_module.c
> +    }
```suggestion
```

2023-10-11 16:47 UTC, RekGRpth commented on ngx_http_captcha_module.c
> -    if (!conf->secret.len) return "captcha secret cannot be empty";
this line should be not deleted!

2023-10-16 16:33 UTC, vvvllll commented on ngx_http_captcha_module.c
> -    if (!conf->secret.len) return "captcha secret cannot be empty";
It doesn't compile with it

ngx_http_captcha_module//ngx_http_captcha_module.c: In function 'ngx_http_captcha_merge_loc_conf':
ngx_http_captcha_module//ngx_http_captcha_module.c:244:22: error: 'conf->secret' is a pointer; did you mean to use '->'?
  244 |     if (!conf->secret.len) return "captcha secret cannot be empty";
      |                      ^
      |                      ->

2023-10-16 16:34 UTC, vvvllll reviewed
Still broken for me, "code" contains invalid value after adding the line 

    if (ngx_http_complex_value(r, location->secret, &secret) != NGX_OK) { ngx_log_error(NGX_LOG_ERR, r->connection->log, 0, "ngx_http_complex_value != NGX_OK"); return NGX_HTTP_INTERNAL_SERVER_ERROR; }

it contains arbitrary data

Which makes the md5 always wrong

2023-10-18 13:58 UTC, vvvllll commented on ngx_http_captcha_module.c
> +    ngx_log_error(NGX_LOG_WARN, r->connection->log, 0, "secret0 %s", code);
Still corrupts "code"

2023-10-28 05:07 UTC, RekGRpth commented
I apply you commit and add fix

2023-10-28 05:07 UTC, closed without merging